# Generated by Django 4.1.1 on 2022-09-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(blank=True, max_length=100, verbose_name="address"),
        ),
    ]
