# Generated by Django 4.1.1 on 2022-09-28 04:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0002_customuser_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="name"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GPU", "Graphic Card"),
                            ("CPU", "Precessor"),
                            ("MB", "Motherboard"),
                            ("RAM", "Random Access Memory"),
                            ("SSD", "Solid State Drive"),
                            ("HDD", "Hard Drive Disk"),
                            ("PS", "Power Supply"),
                            ("CS", "Case"),
                            ("FN", "Fan"),
                            ("OS", "Operation System"),
                            ("AV", "Anti Virus"),
                            ("MS", "Mouse"),
                            ("KB", "Keyboard"),
                            ("HP", "Headphones"),
                            ("MT", "Monitor"),
                            ("MP", "Microphone"),
                            ("GC", "Gaming Chair"),
                        ],
                        max_length=3,
                        verbose_name="category",
                    ),
                ),
                ("is_avaiable", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                help_text="Required.",
                max_length=20,
                region=None,
                unique=True,
                verbose_name="phone",
            ),
        ),
    ]
