# Generated by Django 4.1.1 on 2022-09-28 04:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0003_component_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                help_text="Required. Must start with '+7' and contains 11 digits.",
                max_length=20,
                region="RU",
                unique=True,
                verbose_name="phone",
            ),
        ),
    ]
