# Generated by Django 4.1.1 on 2022-09-28 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0005_component_price_alter_component_is_avaiable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentImage",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "path",
                    models.ImageField(
                        upload_to="images/<django.db.models.fields.UUIDField>/",
                        verbose_name="image",
                    ),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="is main")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="toronto.component",
                    ),
                ),
            ],
        ),
    ]
