# Generated by Django 4.1.1 on 2022-09-28 05:26

from django.db import migrations, models
import toronto.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0006_componentimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d01afe7b-c8a5-45a9-8cf9-38b0795f40dc"),
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="componentimage",
            name="path",
            field=models.ImageField(
                upload_to=toronto.models.ComponentImage.get_directory_path,
                verbose_name="image",
            ),
        ),
    ]
