# Generated by Django 4.1.1 on 2022-09-28 05:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0007_alter_componentimage_id_alter_componentimage_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
        ),
        migrations.AlterField(
            model_name="componentimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9be40626-85f5-4956-8cc3-64fc29c6b61d"),
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.CreateModel(
            name="SpecificationInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="value")),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="toronto.component",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="toronto.specification",
                    ),
                ),
            ],
        ),
    ]
