# Generated by Django 4.1.1 on 2022-09-28 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0008_specification_alter_componentimage_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specification",
            name="name",
        ),
        migrations.AddField(
            model_name="component",
            name="specifications",
            field=models.ManyToManyField(
                to="toronto.specification", verbose_name="component specification"
            ),
        ),
        migrations.AddField(
            model_name="specification",
            name="category",
            field=models.CharField(
                choices=[("MOD", "Model"), ("SOK", "Socket"), ("YR", "Release year")],
                max_length=3,
                null=True,
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="specification",
            name="value",
            field=models.CharField(default="MOD", max_length=100, verbose_name="value"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="componentimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4957c1f0-7834-4dcd-b599-bccd75aa9efe"),
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.DeleteModel(
            name="SpecificationInstance",
        ),
    ]
