# Generated by Django 4.1.1 on 2022-09-28 06:18

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0009_remove_specification_name_component_specifications_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specification",
            options={
                "verbose_name": "specification",
                "verbose_name_plural": "specifications",
            },
        ),
        migrations.AlterField(
            model_name="componentimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("96f5bb71-1e00-4693-af93-f7e3403186de"),
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                help_text="Required. Must start with '+7' and contains 11 digits.",
                max_length=20,
                region="RU",
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
