# Generated by Django 4.1.1 on 2022-09-28 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "toronto",
            "0010_alter_specification_options_alter_componentimage_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("34f9be18-ef1c-48ca-a7bf-33275eb536be"),
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("summary", models.TextField(max_length=400, verbose_name="summary")),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "components",
                    models.ManyToManyField(
                        to="toronto.component", verbose_name="configuration components"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
