# Generated by Django 4.1.1 on 2022-09-28 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0011_alter_componentimage_id_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a901a56a-7e48-4bf6-a4f5-8c64784a0986"),
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="address")),
                (
                    "prepaid",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="prepaid"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="price"
                    ),
                ),
                ("status", models.CharField(max_length=2, verbose_name="status")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date created"
                    ),
                ),
                (
                    "date_closed",
                    models.DateTimeField(null=True, verbose_name="date closed"),
                ),
                (
                    "date_canceled",
                    models.DateTimeField(null=True, verbose_name="date canceled"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
