# Generated by Django 4.1.1 on 2022-09-28 07:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0012_alter_componentimage_id_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="toronto.order",
            ),
        ),
        migrations.AlterField(
            model_name="componentimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1ac54f5d-c00b-4033-9301-76cc4a8de6f1"),
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
    ]
