# Generated by Django 4.1.1 on 2022-09-28 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("toronto", "0013_configuration_order_alter_componentimage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentimage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a881c81a-662b-49cd-a0c4-ea559294e346"),
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="prepaid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="prepaid"
            ),
        ),
    ]
